-- ============================================================
-- SEED — OKR estratégicos Q3 2026 (Tonny Dager x ExperientIA).
-- Carga los objetivos y resultados clave del documento estratégico.
-- Idempotente: solo inserta si la tabla okrs está vacía. Seguro de re-ejecutar.
-- Requiere: 2026_q1_planeacion.sql (tabla okrs).
-- ============================================================
SET NAMES utf8mb4;

INSERT INTO okrs (objective, quarter, owner, key_results, progress, status, position)
SELECT * FROM (
  SELECT 'Instalar a Tonny Dager como autoridad visible en crecimiento empresarial.' AS objective, '2026-Q3' AS quarter, 'Tonny Dager' AS owner, '[{"text":"Publicar 5 contenidos semanales (LinkedIn + Instagram)","current":"0","target":"5/sem"},{"text":"Impresiones acumuladas en LinkedIn","current":"0","target":"30.000"},{"text":"Visualizaciones acumuladas en Instagram","current":"0","target":"50.000"},{"text":"Interacciones cualificadas (comentarios, DMs, respuestas)","current":"0","target":"300"},{"text":"Conversaciones directas con empresarios o líderes","current":"0","target":"90"}]' AS key_results, 0 AS progress, 'activo' AS status, 1 AS position UNION ALL
  SELECT 'Convertir la autoridad de Tonny en diagnósticos comerciales.' AS objective, '2026-Q3' AS quarter, 'Tonny Dager' AS owner, '[{"text":"Formularios del Diagnóstico Tablero de Crecimiento","current":"0","target":"90"},{"text":"Lecturas estratégicas agendadas","current":"0","target":"30"},{"text":"Lecturas convertidas en propuestas","current":"0","target":"12"},{"text":"Oportunidades pagas cerradas","current":"0","target":"6"},{"text":"Tasa de conversión reunión a propuesta","current":"0%","target":"30%"}]' AS key_results, 0 AS progress, 'activo' AS status, 2 AS position UNION ALL
  SELECT 'Instalar El Tablero de Crecimiento como símbolo propietario.' AS objective, '2026-Q3' AS quarter, 'Tonny Dager' AS owner, '[{"text":"Piezas centradas en el framework","current":"0","target":"15"},{"text":"Lead magnet del diagnóstico","current":"0","target":"1"},{"text":"Webinars o lives sobre el tablero","current":"0","target":"2"},{"text":"Ebook o guía descargable","current":"0","target":"1"},{"text":"Personas que comenten o soliciten la palabra TABLERO","current":"0","target":"50"}]' AS key_results, 0 AS progress, 'activo' AS status, 3 AS position UNION ALL
  SELECT 'Convertir la autoridad institucional en confianza comercial.' AS objective, '2026-Q3' AS quarter, 'ExperientIA' AS owner, '[{"text":"Contenidos semanales desde ExperientIA","current":"0","target":"3/sem"},{"text":"Pruebas, casos, procesos o dashboards documentados","current":"0","target":"6"},{"text":"Piezas de método publicadas","current":"0","target":"9"},{"text":"Carruseles técnicos (datos, IA, automatización)","current":"0","target":"3"},{"text":"Conversaciones comerciales desde la marca","current":"0","target":"20"}]' AS key_results, 0 AS progress, 'activo' AS status, 4 AS position UNION ALL
  SELECT 'Convertir el Tablero de Crecimiento en oferta consultiva.' AS objective, '2026-Q3' AS quarter, 'ExperientIA' AS owner, '[{"text":"Landing del Diagnóstico Tablero (antes del 5 jul)","current":"Pendiente","target":"Listo"},{"text":"Formulario diagnóstico (antes del 1 jul)","current":"Pendiente","target":"Listo"},{"text":"Página de gracias con agenda (antes del 5 jul)","current":"Pendiente","target":"Listo"},{"text":"Propuesta comercial base (antes del 10 jul)","current":"Pendiente","target":"Listo"},{"text":"3 niveles de oferta: diagnóstico, sprint, implementación","current":"0","target":"3"}]' AS key_results, 0 AS progress, 'activo' AS status, 5 AS position UNION ALL
  SELECT 'Cerrar ventas consultivas asociadas al framework.' AS objective, '2026-Q3' AS quarter, 'ExperientIA' AS owner, '[{"text":"Pipeline mensual generado (USD)","current":"0","target":"40.000"},{"text":"Propuestas comerciales mensuales","current":"0","target":"4"},{"text":"Cierre mensual (USD)","current":"0","target":"10.000"},{"text":"Implementación premium en Q3","current":"0","target":"1"},{"text":"Sprints o diagnósticos pagos en Q3","current":"0","target":"3"}]' AS key_results, 0 AS progress, 'activo' AS status, 6 AS position UNION ALL
  SELECT 'Construir una narrativa de mercado clara.' AS objective, '2026-Q3' AS quarter, 'Conjunto' AS owner, '[{"text":"Piezas con el mensaje: si no tienes tablero, estás reaccionando","current":"0","target":"20"},{"text":"Piezas con El Tablero como recurso visual","current":"0","target":"25"},{"text":"CTA único en julio: comenta TABLERO","current":"Pendiente","target":"Activo"},{"text":"Piezas colaborativas Tonny + ExperientIA por mes","current":"0","target":"4/mes"},{"text":"Caso o aplicación real por semana (desde agosto)","current":"0","target":"1/sem"}]' AS key_results, 0 AS progress, 'activo' AS status, 7 AS position UNION ALL
  SELECT 'Activar una máquina mínima de demanda.' AS objective, '2026-Q3' AS quarter, 'Conjunto' AS owner, '[{"text":"Link en bio activo (antes del 1 jul)","current":"Pendiente","target":"Listo"},{"text":"Formulario diagnóstico activo (antes del 1 jul)","current":"Pendiente","target":"Listo"},{"text":"Agenda de lectura estratégica activa (antes del 1 jul)","current":"Pendiente","target":"Listo"},{"text":"Registrar todos los leads en CRM desde el día 1","current":"Pendiente","target":"Activo"},{"text":"Revisar métricas todos los viernes","current":"Pendiente","target":"Semanal"}]' AS key_results, 0 AS progress, 'activo' AS status, 8 AS position UNION ALL
  SELECT 'Convertir contenido en conversaciones comerciales.' AS objective, '2026-Q3' AS quarter, 'Conjunto' AS owner, '[{"text":"DMs mensuales","current":"0","target":"30"},{"text":"Reuniones mensuales","current":"0","target":"10"},{"text":"Propuestas mensuales","current":"0","target":"4"},{"text":"Cierres mensuales","current":"0","target":"2"},{"text":"Seguimiento a cada lead en máximo 48 horas","current":"Pendiente","target":"48h"}]' AS key_results, 0 AS progress, 'activo' AS status, 9 AS position
) seed
WHERE NOT EXISTS (SELECT 1 FROM okrs LIMIT 1);
